/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeMockQuicProfiler {
  constructor(options: JsMockQuicProfileOptions, callback: (err: Error | null, events: Array<JsH3Event>) => void)
  pollResultJson(): string | null
  shutdown(): void
}

export declare class NativeQuicClient {
  constructor(options: JsQuicClientOptions, callback: (err: Error | null, events: Array<JsH3Event>) => void)
  connect(serverAddr: string, serverName: string): JsAddressInfo
  openStream(): number
  streamSend(streamId: number, data: Buffer, fin: boolean): JsStreamSendOutcome
  streamClose(streamId: number, errorCode: number): boolean
  close(errorCode: number, reason: string): boolean
  sendDatagram(data: Buffer): boolean
  localAddress(): JsAddressInfo
  getSessionMetrics(): JsSessionMetrics
  ping(): boolean
  getQlogPath(): string | null
  /** Send the Shutdown command without joining the worker thread. */
  requestShutdown(): boolean
  /** Audit finding #14: see Http3SecureServer::ack_event_batch. */
  ackEventBatch(count: number): void
  /**
   * Join the worker thread. Safe to call after `request_shutdown()`.
   * Also releases the TSFN reference held by this struct.
   */
  joinWorker(): void
  shutdown(): void
}

export declare class NativeQuicServer {
  constructor(options: JsQuicServerOptions, callback: (err: Error | null, events: Array<JsH3Event>) => void)
  listen(port: number, host: string): JsAddressInfo
  streamSend(connHandle: number, streamId: number, data: Buffer, fin: boolean): JsStreamSendOutcome
  streamClose(connHandle: number, streamId: number, errorCode: number): boolean
  closeSession(connHandle: number, errorCode: number, reason: string): boolean
  sendDatagram(connHandle: number, data: Buffer): boolean
  localAddress(): JsAddressInfo
  getSessionMetrics(connHandle: number): JsSessionMetrics
  pingSession(connHandle: number): boolean
  getQlogPath(connHandle: number): string | null
  /** Send the Shutdown command without joining the worker threads. */
  requestShutdown(): boolean
  /** Audit finding #14: see Http3SecureServer::ack_event_batch. */
  ackEventBatch(count: number): void
  /**
   * Join all worker threads. Safe to call after `request_shutdown()`.
   * Also releases the TSFN reference held by this struct.
   */
  joinWorker(): void
  shutdown(): void
}

/** Worker-thread client: Rust owns UDP I/O, polling, timers, and QUIC/H3 processing. */
export declare class NativeWorkerClient {
  constructor(options: JsClientOptions, callback: (err: Error | null, events: Array<JsH3Event>) => void)
  connect(serverAddr: string, serverName: string): JsAddressInfo
  sendRequest(headers: Array<JsHeader>, fin: boolean): number
  streamSend(streamId: number, data: Buffer, fin: boolean): JsStreamSendOutcome
  streamClose(streamId: number, errorCode: number): boolean
  close(errorCode: number, reason: string): boolean
  sendDatagram(data: Buffer): boolean
  localAddress(): JsAddressInfo
  getSessionMetrics(): JsSessionMetrics
  getRemoteSettings(): Array<JsSetting>
  ping(): boolean
  getQlogPath(): string | null
  /** Send the Shutdown command without joining the worker thread. */
  requestShutdown(): boolean
  /** Audit finding #14: see Http3SecureServer::ack_event_batch. */
  ackEventBatch(count: number): void
  /** Join the worker thread. Safe to call after `request_shutdown()`. */
  joinWorker(): void
  shutdown(): void
}

export declare class NativeWorkerServer {
  constructor(options: JsServerOptions, callback: (err: Error | null, events: Array<JsH3Event>) => void)
  /**
   * Start the worker thread, binding to the given address.
   * Returns the bound address info.
   */
  listen(port: number, host: string): JsAddressInfo
  /** Send a command to the worker. Returns false if backpressure (queue full). */
  sendResponseHeaders(connHandle: number, streamId: number, headers: Array<JsHeader>, fin: boolean): boolean
  /**
   * Combined headers + body + FIN in a single NAPI call — avoids 2 extra
   * FFI boundary crossings for the common respond-then-end pattern.
   */
  sendResponse(connHandle: number, streamId: number, headers: Array<JsHeader>, data: Buffer, fin: boolean): boolean
  streamSend(connHandle: number, streamId: number, data: Buffer, fin: boolean): JsStreamSendOutcome
  sendTrailers(connHandle: number, streamId: number, headers: Array<JsHeader>): boolean
  streamClose(connHandle: number, streamId: number, errorCode: number): boolean
  closeSession(connHandle: number, errorCode: number, reason: string): boolean
  sendDatagram(connHandle: number, data: Buffer): boolean
  localAddress(): JsAddressInfo
  getSessionMetrics(connHandle: number): JsSessionMetrics
  getRemoteSettings(connHandle: number): Array<JsSetting>
  pingSession(connHandle: number): boolean
  getQlogPath(connHandle: number): string | null
  /** Send the Shutdown command without joining the worker threads. */
  requestShutdown(): boolean
  /**
   * Audit finding #14: JS calls this after dispatching a TSFN batch
   * so the worker can quantify how far behind real-time JS is.
   * Releases credit on the global outstanding-events gauge; the
   * recv-pause threshold (step 5.2) reads that gauge to decide
   * whether to skip RX processing for one poll iteration.
   */
  ackEventBatch(count: number): void
  /** Join all worker threads. Safe to call after `request_shutdown()`. */
  joinWorker(): void
  shutdown(): void
}

export interface JsAddressInfo {
  address: string
  family: string
  port: number
}

export interface JsClientOptions {
  ca?: ByteBuf
  rejectUnauthorized?: boolean
  runtimeMode?: string
  maxIdleTimeoutMs?: number
  maxUdpPayloadSize?: number
  initialMaxData?: number
  initialMaxStreamDataBidiLocal?: number
  initialMaxStreamsBidi?: number
  sessionTicket?: ByteBuf
  allow0Rtt?: boolean
  enableDatagrams?: boolean
  keylog?: boolean
  qlogDir?: string
  qlogLevel?: string
  /**
   * Disable quiche's send pacing. Sans-IO/wasm callers have no way to
   * honor sub-ms `SendInfo` release times (A2 task 4) — plumbing exists
   * here for that profile; native behavior is unaffected unless a
   * caller explicitly opts in.
   */
  disablePacing?: boolean
}

/**
 * Metadata for rare events (new_session, error, reset).
 * Packed into a sub-object to avoid 5 null napi properties on every hot-path event.
 */
export interface JsEventMeta {
  errorCode?: number
  errorReason?: string
  errorCategory?: string
  remoteAddr?: string
  remotePort?: number
  serverName?: string
  reasonCode?: string
  runtimeDriver?: string
  runtimeMode?: string
  requestedRuntimeMode?: string
  fallbackOccurred?: boolean
  errno?: number
  syscall?: string
  peerCertificatePresented?: boolean
  peerCertificateChain?: Array<ByteBuf>
  durationMs?: number
}

export interface JsH3Event {
  eventType: number
  connHandle: number
  streamId: number
  headers?: Array<JsHeader>
  data?: ByteBuf
  fin?: boolean
  meta?: JsEventMeta
  metrics?: JsSessionMetrics
}

export interface JsHeader {
  name: string
  value: string
}

export interface JsLifecycleTraceEvent {
  seq: number
  timestampMs: number
  component: string
  action: string
  driver?: string
  batchSize?: number
  pendingTx?: number
  note?: string
}

export interface JsLifecycleTraceSnapshot {
  enabled: boolean
  capacity: number
  droppedEvents: number
  eventCount: number
  events: Array<JsLifecycleTraceEvent>
}

export interface JsMockQuicProfileOptions {
  key: Buffer
  cert: Buffer
  ca?: Buffer
  alpn?: Array<string>
  rejectUnauthorized?: boolean
  serverName?: string
  streamsPerConnection?: number
  payloadBytes?: number
  responseFragmentCount?: number
  responseFragmentSize?: number
  timeoutMs?: number
  sinkMode?: string
  replayTraceJson?: string
}

export interface JsQuicClientOptions {
  ca?: ByteBuf
  cert?: ByteBuf
  key?: ByteBuf
  rejectUnauthorized?: boolean
  alpn?: Array<string>
  runtimeMode?: string
  maxIdleTimeoutMs?: number
  maxUdpPayloadSize?: number
  initialMaxData?: number
  initialMaxStreamDataBidiLocal?: number
  initialMaxStreamsBidi?: number
  sessionTicket?: ByteBuf
  allow0Rtt?: boolean
  enableDatagrams?: boolean
  keylog?: boolean
  qlogDir?: string
  qlogLevel?: string
  /** Disable quiche's send pacing (see `JsClientOptions::disable_pacing`). */
  disablePacing?: boolean
}

export interface JsQuicServerOptions {
  key: ByteBuf
  cert: ByteBuf
  ca?: ByteBuf
  clientAuth?: string
  alpn?: Array<string>
  runtimeMode?: string
  maxIdleTimeoutMs?: number
  maxUdpPayloadSize?: number
  initialMaxData?: number
  initialMaxStreamDataBidiLocal?: number
  initialMaxStreamsBidi?: number
  disableActiveMigration?: boolean
  enableDatagrams?: boolean
  maxConnections?: number
  disableRetry?: boolean
  qlogDir?: string
  qlogLevel?: string
  sessionTicketKeys?: ByteBuf
  keylog?: boolean
}

export interface JsReactorTelemetrySnapshot {
  driverSetupAttemptsTotal: number
  driverSetupSuccessTotal: number
  driverSetupFailureTotal: number
  ioUringDriverSetupAttempts: number
  ioUringDriverSetupSuccesses: number
  ioUringDriverSetupFailures: number
  pollDriverSetupAttempts: number
  pollDriverSetupSuccesses: number
  pollDriverSetupFailures: number
  kqueueDriverSetupAttempts: number
  kqueueDriverSetupSuccesses: number
  kqueueDriverSetupFailures: number
  workerThreadSpawnsTotal: number
  workerThreadStopsTotal: number
  workerLoopExitByCommandTotal: number
  workerLoopExitByHandlerDoneTotal: number
  workerLoopExitBySinkCloseTotal: number
  workerLoopExitByRuntimeErrorTotal: number
  shutdownCompleteEmittedTotal: number
  eventBatchFlushesTotal: number
  eventBatchAttemptedEventsTotal: number
  eventBatchDeliveredEventsTotal: number
  eventBatchDroppedEventsTotal: number
  eventBatchSinkErrorsTotal: number
  eventBatchMaxSizeHighWatermark: number
  eventBatchAckedEventsTotal: number
  eventBatchOutstanding: number
  eventBatchOutstandingHighWatermark: number
  eventBatchSelfHealedTotal: number
  /**
   * Audit #14, step 5.2: count of poll iterations where JS-facing
   * protocol event production was paused because the outstanding-events
   * gauge was over the high-water mark. Coarse backpressure signal — if
   * this climbs without bound, JS dispatch is the bottleneck.
   */
  eventBatchRxPausesTotal: number
  /**
   * Audit #18: ECN observability — counts of inbound datagrams by
   * code point. Telemetry only (quiche 0.28 doesn't expose ECN).
   */
  ecnRecvNotEctTotal: number
  ecnRecvEct0Total: number
  ecnRecvEct1Total: number
  ecnRecvCeTotal: number
  rawQuicServerWorkerSpawns: number
  rawQuicClientDedicatedWorkerSpawns: number
  rawQuicClientSharedWorkersCreated: number
  rawQuicClientSharedWorkerReuses: number
  h3ServerWorkerSpawns: number
  h3ClientDedicatedWorkerSpawns: number
  h3ClientSharedWorkersCreated: number
  h3ClientSharedWorkerReuses: number
  clientLocalPortReuseHits: number
  rawQuicClientSessionsOpened: number
  rawQuicClientSessionsClosed: number
  rawQuicFinObservations: number
  rawQuicFinishedEventEmits: number
  rawQuicDrainEventEmits: number
  rawQuicBlockedStreamHighWatermark: number
  rawQuicClientPendingWriteHighWatermark: number
  rawQuicClientReapsWithPendingWrites: number
  rawQuicClientReapsWithBlockedStreams: number
  rawQuicClientReapsWithKnownStreams: number
  rawQuicClientCloseByPacket: number
  rawQuicClientCloseByTimeout: number
  rawQuicClientCloseByShutdown: number
  rawQuicClientCloseByRelease: number
  rawQuicServerSessionsOpened: number
  rawQuicServerSessionsClosed: number
  h3ClientSessionsOpened: number
  h3ClientSessionsClosed: number
  h3ServerSessionsOpened: number
  h3ServerSessionsClosed: number
  ioUringRxInFlightHighWatermark: number
  ioUringTxInFlightHighWatermark: number
  ioUringPendingTxHighWatermark: number
  ioUringTier2DrainRounds: number
  ioUringTier2TaskrunPrefetches: number
  ioUringTier2BlockingWaits: number
  ioUringTier2CapHits: number
  ioUringRetryableSendCompletions: number
  ioUringSubmitCalls: number
  ioUringSubmitWithArgsCalls: number
  ioUringSubmittedSqesTotal: number
  ioUringCompletionTotal: number
  ioUringCompletionBatchHighWatermark: number
  ioUringWakeCompletions: number
  ioUringWakeWrites: number
  ioUringTimeoutPolls: number
  ioUringRxDatagramsTotal: number
  ioUringTxDatagramsSubmittedTotal: number
  ioUringTxDatagramsCompletedTotal: number
  ioUringSqFullEvents: number
  kqueueUnsentHighWatermark: number
  kqueueWouldBlockSends: number
  kqueueWriteWakeups: number
  kqueueMsgXProbeSuccesses: number
  kqueueMsgXProbeFailures: number
  kqueueSendmsgXEnabled: number
  kqueueRecvmsgXEnabled: number
  kqueueSendmsgXSubmitCalls: number
  kqueueSendmsgXDatagramsSubmitted: number
  kqueueSendmsgXPartialSends: number
  kqueueSendmsgXFallbacks: number
  kqueueRecvmsgXCalls: number
  kqueueRecvmsgXDatagramsReceived: number
  kqueueRecvmsgXFallbacks: number
  rxBufferReuses: number
  rxBufferAllocations: number
  rxBufferCheckins: number
  rxBufferDrops: number
  rxBufferCopiedBytes: number
  groSegmentBufferReuses: number
  groSegmentBufferAllocations: number
  groSegmentBufferCheckins: number
  groSegmentBufferDrops: number
  groSegmentBufferCopiedBytes: number
  pendingWriteBufferReuses: number
  pendingWriteBufferAllocations: number
  pendingWriteBufferCheckins: number
  pendingWriteBufferDrops: number
  pendingWriteCopiedBytes: number
  pendingWriteTailAllocations: number
  pendingWriteGrowthReallocations: number
  outboundIngressBufferReuses: number
  outboundIngressBufferAllocations: number
  outboundIngressCopiedBytes: number
  outboundStreamJsAdmittedBytesTotal: number
  outboundStreamJsAdmittedWritesTotal: number
  outboundCommandQueuedBytes: number
  outboundCommandQueuedBytesHighWatermark: number
  outboundPendingWriteBytes: number
  outboundPendingWriteBytesHighWatermark: number
  outboundAdmissionBackpressureEventsTotal: number
  outboundAdmissionReleasedUnitsTotal: number
  outboundAdmissionWriteReadyEventsTotal: number
  txBuffersRecycled: number
}

export interface JsServerOptions {
  key: ByteBuf
  cert: ByteBuf
  ca?: ByteBuf
  runtimeMode?: string
  maxIdleTimeoutMs?: number
  maxUdpPayloadSize?: number
  initialMaxData?: number
  initialMaxStreamDataBidiLocal?: number
  initialMaxStreamsBidi?: number
  disableActiveMigration?: boolean
  enableDatagrams?: boolean
  qpackMaxTableCapacity?: number
  qpackBlockedStreams?: number
  recvBatchSize?: number
  sendBatchSize?: number
  qlogDir?: string
  qlogLevel?: string
  sessionTicketKeys?: ByteBuf
  maxConnections?: number
  disableRetry?: boolean
  reusePort?: boolean
  keylog?: boolean
  quicLb?: boolean
  serverId?: ByteBuf
}

export interface JsSessionMetrics {
  packetsIn: number
  packetsOut: number
  bytesIn: number
  bytesOut: number
  handshakeTimeMs: number
  rttMs: number
  cwnd: number
  pmtu: number
  datagramQueueDepth: number
}

export interface JsSetting {
  id: number
  value: number
}

export interface JsStreamSendOutcome {
  status: number
  written: number
}

export declare function lifecycleTraceSnapshot(): JsLifecycleTraceSnapshot

export declare function resetLifecycleTrace(): void

export declare function resetRuntimeTelemetry(): void

export declare function runtimeTelemetry(): JsReactorTelemetrySnapshot

export declare function setLifecycleTraceEnabled(enabled: boolean): void

export declare function version(): string
